.PHONY: clean All

All:
	@echo "----------Building project:[ Section7Challenge - Debug ]----------"
	@cd "Section7Challenge" && "$(MAKE)" -f  "Section7Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section7Challenge - Debug ]----------"
	@cd "Section7Challenge" && "$(MAKE)" -f  "Section7Challenge.mk" clean
