.PHONY: clean All

All:
	@echo "----------Building project:[ Section8challenge - Debug ]----------"
	@cd "Section8challenge" && "$(MAKE)" -f  "Section8challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section8challenge - Debug ]----------"
	@cd "Section8challenge" && "$(MAKE)" -f  "Section8challenge.mk" clean
