.PHONY: clean All

All:
	@echo "----------Building project:[ Section12 - Debug ]----------"
	@cd "C:\Users\ricto\Desktop\CPPExamples\Section12\Section12" && "$(MAKE)" -f  "Section12.mk"
clean:
	@echo "----------Cleaning project:[ Section12 - Debug ]----------"
	@cd "C:\Users\ricto\Desktop\CPPExamples\Section12\Section12" && "$(MAKE)" -f  "Section12.mk" clean
